### ISSUE TITLE
.exe hangs on exit

### ISSUE THREAD

**Issue by patxu** [patxu/cs98-senior-project#105]

**Comment by patxu** [comment]
https://github.com/patxu/cs98-senior-project/blob/master/climbARUnity/Assets/3_GameScene/Scripts/KinectClassify.cs#L70

**Comment by db2882** [comment]
Fixed with workaround:

if (Application.isEditor)
        {
            Debug.Log("Cannot quit the application (Application is editor).");
        }
        else
        {
            System.Diagnostics.Process.GetCurrentProcess().Kill();
        }
