### ISSUE TITLE
Smooth hand to hold grab detection

### ISSUE THREAD

**Issue by relchar** [patxu/cs98-senior-project#107]

**Comment by relchar** [comment]
http://www.contentmaster.com/kinect/kinect-sdk-smoothing-skeleton-data/

--> projection seems to add noise to the skeleton and hand hold grabbing detection

**Comment by db2882** [comment]
Turning off and on music tracks is very difficult without smoothing. they keep jumping on and off

**Comment by patxu** [comment]
https://github.com/patxu/cs98-senior-project/pull/174
