### ISSUE TITLE
Potential hang during classification coroutine

### ISSUE THREAD

**Issue by db2882** [patxu/cs98-senior-project#119]
Pressing 'c' leads to the logged "starting classification coroutine" but no number of holds found is ever returned. Perhaps introduced in https://github.com/patxu/cs98-senior-project/commit/81320e0486232ff73be2db545f93b9f77597eb40 ?

**Comment by patxu** [comment]
seems somewhat fixed now - could be related to the classifier not finding any holds and us interpreting that as a hang

error checking in 8748e131c6480c508fd3a0417c27bb75fb663ff7
