### ISSUE TITLE
OpenCV dll won't recognize holds

### ISSUE THREAD

**Issue by db2882** [patxu/cs98-senior-project#121]
At some point it appears we messed up the opencv plugin. When building with the code found on master, the dll runs without error but returns zero holds. The DLL from pat's computer (posted in the slack) works but was last built in early november

**Comment by db2882** [comment]
In commit: https://github.com/patxu/cs98-senior-project/commit/73a0c3aff6ea1e063e8594ee31afd3f16433d961 we change the function name to its current name of classifyImage. Since pat's dll runs when calling this function name we know it must have been built post this commit.

**Comment by patxu** [comment]
#123
