### ISSUE TITLE
Avoid collisions between similar game objects

### ISSUE THREAD

**Issue by relchar** [patxu/cs98-senior-project#132]
- Avoid collisions between ghosts
- Avoid collisions between ghosts and handholds
- Only the skeleton should collide with either

**Comment by patxu** [comment]
maybe we need to figure out how to abstract our colliders so it's easy to tell them which things to collide with and which things they shouldn't

**Comment by patxu** [comment]
David here. I agree a more general abstraction would be nice. Currently, we prevent hold-hold collision by looking at the tag on the collider and if it 'Hold', ignoring the collision. This approach is simple with one type of game object but probably wouldn't scale well with many types of game objects.

**Comment by patxu** [comment]
#257 

still just doing a check to see if the collider has tag "hold"
since there's only one ghost i'm closing this issue
