### ISSUE TITLE
Work on skeleton movement smoothing - appears to shake/jump around a lot

### ISSUE THREAD

**Issue by nmoolenijzer** [patxu/cs98-senior-project#172]
Currently, the skeleton projection appears to move around a lot/jump around as the user tries to select a handhold - discussion in class made it seem like this might just be a whiteboard issue, but would be good to validate that that's the case

**Comment by patxu** [comment]
Fixed with 83b357f 

Only consider one collision a second, and only worry about first joint in collision. Ignore other joints that collide while first joint is on hold.
