### ISSUE TITLE
Hide "No hands detected" warning on detect holds scene

### ISSUE THREAD

**Issue by patxu** [patxu/cs98-senior-project#193]
The projected text might mess up the classifier

**Comment by patxu** [comment]
Fixed with 177a10c

**Comment by patxu** [comment]
this seems to have been introduced again. i tried to fix it and it should work but something still seems to be wrong. i was kind of in a limbo state with some other important changes so  i ended up just committing my attempt. shouldn't be too hard to pick back up. @db2882 maybe we can take a look tomorrow 

https://github.com/patxu/cs98-senior-project/blob/master/climbARUnity/Assets/Kinect/Scripts/KinectClassify.cs#L105

https://github.com/patxu/cs98-senior-project/blob/master/climbARUnity/Assets/Kinect/Scripts/BodySourceView.cs#L126

**Comment by patxu** [comment]
this is hi pri bc it makes it hard to classify holds automatically

**Comment by olykos** [comment]
Fixed with #287. You basically had done all the work, just a small logic error where enabled needed to be actively set to false during classification. \- @db2882

**Comment by patxu** [comment]
haha thanks, guess i wasn't making thinking clearly at 2am
