### ISSUE TITLE
Classification performance seems to be worse with auto detection

### ISSUE THREAD

**Issue by olykos** [patxu/cs98-senior-project#263]
Is this just me or have other people been finding this? My guess is we might not be waiting long enough after switching the screen to black before we grab a frame and classify off of it. I imagine there is some lag between when we change the color and when the actual projector changes color. Is it possible this is slower than the code running? - @db2882

**Comment by patxu** [comment]
tested with the projector on and off with no delay. it works perfectly with the projector turned off and fails to find all the holds with the projector on. we need to add a delay here to give the unity game a chance tot urn the screen off. 

still having weird issues with the c++ code returning error

**Comment by patxu** [comment]
seems to be working on master once we started using the correct classifier xml

https://github.com/patxu/cs98-senior-project/blob/master/climbARUnity/Assets/Kinect/Scripts/KinectClassify.cs#L39

**Comment by jpkramer** [comment]
still not working with projectoor displaying

**Comment by patxu** [comment]
still not working while projector is still displaying. need to do some sort of delay

**Comment by patxu** [comment]
#285
