### ISSUE TITLE
savedstate.xml not being ignored (might be committed already?)

### ISSUE THREAD

**Issue by patxu** [patxu/cs98-senior-project#284]

**Comment by olykos** [comment]
I changed the path. (And forgot to update .gitignore)

David fixed the gitignore in his branch but I'm guessing it's not merged?

**Comment by patxu** [comment]
interesting ok, we can take a look tomorrow. @db2882

**Comment by db2882** [comment]
Yeah I pushed the gitignore, but its possible when another branch got merged in it got reintroduced. I can track it down tomorrow

**Comment by olykos** [comment]
Should be gone now with #287 \- @db2882
