### ISSUE TITLE
(RocMan) Smooth ghost and skeleton collision

### ISSUE THREAD

**Issue by relchar** [patxu/cs98-senior-project#292]
@db2882, pat asked me to assign you to this since you dealt with kinect skeleton smoothing before this? Right the now the issue is when the skeleton collides with the ghost, we detect the collision too many times, and so the lives we have in the RocMan decrement too quickly (e.g. 4 at a time when it appears that we collide once with the ghost).

**Comment by relchar** [comment]
@patxu tagging you

**Comment by olykos** [comment]
Fixed with #299 \- @db2882
